FROM node:lts-alpine as build

#install deps
RUN apk add --no-cache git python make

# configure server
WORKDIR /opt
RUN git clone https://github.com/AgriculturalEvidence/mical_server server; \
    cd server; \
    npm install; \
    npm run build; \
    rm -rf node_modules;

FROM node:lts-alpine
COPY --from=build /opt/server /opt/server

WORKDIR /opt/server
RUN npm install --production

# if in dev we will expose 8888, otherwise the port will be provided
EXPOSE 8888

CMD node dist/server.js